class Config:
    BUY_THRESHOLD = 0.7  # Adjusted based on analysis
    SELL_THRESHOLD = 0.3  # Adjusted based on analysis
    RISK_FACTOR = 0.02  # Adjusted for potentially higher returns
    LEARNING_RATE = 0.001
    NUM_EPOCHS = 100
    LOT_SIZE_ROUNDING = 8
    TEXTS = ["Bitcoin hits new all-time high", "Ethereum upgrade introduces deflationary mechanism"] # Load up from file generated by gpt
